name: Deploy to staging
on: 
    push:
        branches: [main]
            

jobs: 
    redeploy_everthing:
        runs-on: ubuntu-latest
        name: Deploying everything to the staging cluster
        steps:
          - name: SSH Into server
            run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                ssh -i ~/ssh_key ubuntu@3.25.91.81 
                cd bms_CI_CD && git pull 
                pnpm install 
                pnpm run build 
                pm2 restart  http-server   
                pm2 restart  web  
                pm2 restart  ws-server   
    

